### PR TITLE
Selection jumper 5v/3v, also gnd planes

### PR DESCRIPTION
**Pull request by sebastius**
This should solve #3 by making the voltage to the LT1945 selectable (default at 5v).

Redid some ground traces and planes for better ground coverage.

### CODE REVIEW

**Comment by vroland** [comment]
Looks good so far, thanks for contributing :) 
However, my KiCad (5.1.6) complains about some via clearances (with its default settings, 0.25mm maybe?):
clearances
Could you look into it?

**Comment by sebastius** [comment]
Should be fine: JLC has the following minimum: 5mil (0.127mm)

**Comment by vroland** [comment]
Do you know if that's true for other manufacturers as well? I mean, we should not constrain us here unnecessarily. It seems most of them only need a little wiggle, so I could do it as well.

**Comment by sebastius** [comment]
Feel free to wiggle :)

**Comment by vroland** [comment]
Could you rebase this to remove  fd648a7 and 95a5599?

**Comment by vroland** [comment]
Aand quickly rebase onto the current master? :)

**Comment by sebastius** [comment]
I think i've done it, a friend helped me by telling me what to do ;)

**Comment by vroland** [comment]
@sebastius Is there a specific reason you got rid of the mounting holes? I think it would be nice to have them, though I would be open to moving them to different locations.

**Comment by sebastius** [comment]
I didn't remove the mounting holes on purpose, sorry! They should be there, if i removed them, we'll need to look into bringing them back, or reverting and redoing my mods. Which do you prefer?

**Comment by vroland** [comment]
Ah, probably because they where not in the schematic, to KiCad removed them when updating the PCB. So I would re-add them and move them to their old positions. 
Do you want to do it (and re-position the ground vias) or shoud I do it at some time?

**Pull request merged**
