### PR TITLE
Mountingholes, VCOM testpad and 3d models

### LINKED ISSUE #8: How to calibrate RV1?
Messed with RV1 and now i've got a completely black screen :laughing: , any hints on calibrating RV1 and also recover the eink to normal?

No this is worse. I blew up the opamp... Replaced it and it now works again. Rotating RV1 too close somewhere apparantly blew op U7. 

Regarding the opamp i've submitted a PR to properly close the second opamp, it could be related but not sure.

### PR DESCRIPTION
**Pull request by sebastius**
Fixes #8 and also adds the mountingholes (3x M2) and i've taken the liberty of adding in almost all 3d models.

image

### CODE REVIEW

**Comment by sebastius** [comment]
And i'm sorry its all in one PR, i am very much a novice in GIT and the whole branch stuff doesnt compute in my brain.

**Comment by vroland** [comment]
Thanks! Just to be sure: do you know which license these 3D models are under?

**Comment by sebastius** [comment]
Don't remember, all came from public free websites.

**Comment by vroland** [comment]
Hm, since the board is licensed under CC-By 4.0, it would be good to know if the licenses of 3D-Models are compatible. The simpler parts are probably not really copyrightable (as they lack a creative contribution), but the more complex models might be...
Don't get me wrong, these models look really nice, just want to be on the safe side ;)

**Comment by sebastius** [comment]
The only worry should be the 4 files i included in the repo, the rest is standard Kicad stuff. I’ll try and reconstruct my path in finding them.

**Comment by sebastius** [comment]
Wrover: https://grabcad.com/library/esp32-wrover-b-1 (author says 'no problem' to a similar request)

Button: https://grabcad.com/library/smd-miniature-tactile-switch-5x5x1-5mm-1 (no info included)

panel-connector: https://www.hirose.com/product/p/CL0586-0520-8-55?lang=en

**Comment by vroland** [comment]
Ok, thanks for clarifying. Looks really good, thank you!

**Pull request merged**
