### PR TITLE
Fix Lilygo EPD47 waveform adding ED047TC1 as default #171

### PR DESCRIPTION
**Pull request by martinberlin**
@aceisace please try this branch and tell me if the Grayscale now works correctly for you

### CODE REVIEW

**Comment by aceisace** [comment]
Yes, it does work! I posted an image of it in #171 . Regarding this PR, both waveforms-header files xxtc1 and xxtc2 use the same name `epd_wp_ED047TC1`. Is this supposed to be like this? Second question, how can I use the alternative waveform file (xxtc2)? Do I need to update `boards.txt` or are there additional steps? Thanks in advance

**Comment by martinberlin** [comment]
We could update the variable name to ED047TC2. And add it also in KConfig and as a constant so you can inject it using build flags, does that sound?

**Comment by vroland** [comment]
Note that the timings may be temperature dependent as well. Though if you have done your tests at room temperature it should be fine.

**Review by vroland — APPROVED** [review]

**Comment by martinberlin** [comment]
Thanks @vroland 
About the idea to add both Waveform in KConfig, is a good one?
Or we should leave this as before and add the new one as an **optional** one that can be added?

I just wanted to make thinks as simple as possible. If we add the two we should at least mark them correctly. I suggest something like:

ED047TC1 Fast waveform (similar to Lilygo repository)
ED047TC2 Slower with darker black (7 times bigger in data RAM)

Or something so we can differentiate them. Otherwise I suggest just leaving ED047TC1 and ED047TC2 as extra waveform that needs a small hand modification (uncommenting include and commenting the other one)

**Comment by aceisace** [comment]
I'm in favor of the build flags option as well since it's more space-efficient and more intuitive which waveform was used for the 4.7". Do let me know if I can help with testing 👍

**Comment by martinberlin** [comment]
>I'm in favor of the build flags option as well since it's more space-efficient and more intuitive which waveform was used for the 4.7". Do let me know if I can help with testing

@aceisace please check out latest update. Now I added this in the Kconfig

menuconfig_epdiy

@vroland since this waveform is strangely 7 times bigger, I'm adding the include file only if it's selected, is that alright?  Or it does not really matter?
I just though that we could save some more space for your own program if it is included only when you select that Display.

**Comment by aceisace** [comment]
@martinberlin Thanks for the fast implementation! I'm only using Arduino IDE, will I be able to test the changes there too? If yes, I'll test it soon 👍 
Good luck with moving!

**Pull request merged**
