### PR TITLE
Fontconvert additional argument string

### PR DESCRIPTION
**Pull request by Yardie-**
Add the command line argument 'string'  to fontconvert.py

### CODE REVIEW

**Comment by martinberlin** [comment]
Update looks good to me. Can anyone else try it and submit some feedback?

Thanks for your collaboration.

**Comment by Yardie-** [comment]
Please hold off on this I need to do more testing.

**Comment by martinberlin** [comment]
I will be testing this out this week and weekend so I can provide some feedback. 
I've been busy with client work lately and it's hard to keep up testing EPDiy.

**Comment by Yardie-** [comment]
Thanks @martinberlin. It should be fine but I can't truly know.

**Comment by Yardie-** [comment]
Ok @martinberlin I have done a simple Readme with an example. I have added the help from other scripts in the directory.

**Comment by vroland** [comment]
This looks nice, thanks especially for adding the documentation! I'll soon do some testing, as well :)

**Comment by Yardie-** [comment]
Thanks Valentin @vroland

**Comment by martinberlin** [comment]
@vroland just tested this and re-run the failed tests that where only some external submodules that failed to be fetched. 
Tried it with:

    python  fontconvert.py test 12 /usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf --string abc

And I see that  generates:

```C
// GlyphProps[width, height, advance_x, left, top, compressed_size, data_offset, code_point]
const EpdGlyph test_Glyphs[] = {
    { 0, 0, 6, 0, 0, 0, 0 }, // ' '
    { 11, 13, 13, 1, 13, 78, 0 }, // 'a'
    { 13, 19, 15, 1, 19, 133, 78 }, // 'b'
    { 11, 13, 12, 1, 13, 78, 211 }, // 'c'
};
```

Looks good to me also so if you want to give it last test and merge, feel free.

**Comment by Yardie-** [comment]
Thanks @martinberlin

**Comment by martinberlin** [comment]
@vroland can we merge this?
I think it's very useful to pass as a string the characters you need. And as it does not affect anything I think is safe to merge it.

**Pull request merged**
